AWSTemplateFormatVersion: 2010-09-09

Description: AWS API Gateway Method - Reusable template to create a method (GET|POST|DELETE etc) for the API Gateway Resource resource. 
# Cloudformation reference of API Gateway Method resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html

Parameters:
  RestApiId:
    Description: API Gateway Rest API ID.
    Type: String
  ResourceId:
    Description: Resource ID the method is attach to. 
    Type: String
  HttpMethod:
    Description: Type of method used (GET|POST|DELETE, etc.).
    Type: String
  ApiGatewayRoleArn:
    Description: IAM Role ARN to allow method to access specific resouces.
    Type: String
  Uri:
    Description: URI of resource which is integrated with method.
    Type: String
  AppJsonRequestTemplate:
    Description: Template used to transform request suitable for integrated resource.
    Type: String
  PkRequestParameter:
    Description: (for get methods only) Set the partition key value 
    Type: String
    Default: no-value
  SkRequestParameter:
    Description: (for get methods only) Set the sort key value 
    Type: String
    Default: no-value

Conditions:
  IsGetMethod: !Equals [!Ref HttpMethod, GET]

Resources:
  APIGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApiId # required
      ResourceId: !Ref ResourceId # required
      HttpMethod: !Ref HttpMethod # required
      AuthorizationType: NONE # required
      MethodResponses:
        - StatusCode: 200
      RequestParameters:
        method.request.querystring.pk: !If [IsGetMethod , true, false]
        method.request.querystring.sk: !If [IsGetMethod , true, false]
      Integration:
        !If
          - IsGetMethod
          - Type: AWS
            Credentials: !Ref ApiGatewayRoleArn
            IntegrationHttpMethod: POST
            Uri: !Ref Uri
            RequestParameters:
              integration.request.querystring.pk: !Ref PkRequestParameter
              integration.request.querystring.sk: !Ref SkRequestParameter
            PassthroughBehavior: WHEN_NO_TEMPLATES
            IntegrationResponses:
              - StatusCode: 200
            RequestTemplates: 
              application/json: !Ref AppJsonRequestTemplate
          - Type: AWS
            Credentials: !Ref ApiGatewayRoleArn
            IntegrationHttpMethod: POST
            Uri: !Ref Uri
            PassthroughBehavior: WHEN_NO_TEMPLATES
            IntegrationResponses:
              - StatusCode: 200
            RequestTemplates: 
              application/json: !Ref AppJsonRequestTemplate

Outputs: # Resource outputs used in dependent resources
  MethodId:
    Value: !Ref APIGatewayMethod