AWSTemplateFormatVersion: 2010-09-09

Description: AWS API Gateway Deployment - Reusable template to add Cognito to Rest API authoriser. 
# Cloudformation reference of API Gateway Deployment resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html

Parameters:
  CognitoUserPoolArn:
    Description: Name of the application, to be referenced in tag.
    Type: String
  RestApiId:
    Description: API Gateway Rest API ID.
    Type: String

Resources:
  ApiAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      IdentitySource: method.request.header.authorization
      Name: CognitoAuthorizer
      ProviderARNs: 
       - !Ref CognitoUserPoolArn
      RestApiId: !Ref RestApiId
      Type: COGNITO_USER_POOLS
